id: A8FFEF4F9
title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
type: translation
pechas:
- IE8A0E582
- I59553185
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:42.111356
  last_modified_at: 2023-01-04 12:37:42.111361
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IE8A0E582/8827: EBEF
  I59553185/BB0B: EBEF
